### ISSUE TITLE
Broken Links in README

### ISSUE THREAD

**Issue by Fubinator** [sebastienrousseau/shokunin#10]
Hi, just stumbled across this project and found it interesting. I noticed that the links for Bug Report, Feature Request and Contributing Guidelines are broken in the README file.

I could fix that for you if you'd take a PR for that.

BTW: I'd like to contribute more stuff, but I'm not sure what. So if you have stuff open, feel free to create some issues and I would take a look at it

**Comment by sebastienrousseau** [comment]
@Fubinator Thanks for this, let me have a look at the README file, I owe it some attention. Just making some upgrades at the moment which hopefully you would like.

But feel free to raise any PR for any changes, ideas, updates you would like to bring.

I will create some issues in GitHub but to give you an idea on what I am looking at enhancing at the moment:

- [ ] Increasing unit test coverage
- [ ] Enhancing and optimising the template file and logic
- [ ] Adding other types of content formats to generate from (CSV, YAML, TOML, TXT etc)
- [ ] Creating Criterion.rs tests to assess and enhance performance
- [ ] Enhancing the CLI for better usability
- [ ] Etc.

**Comment by sebastienrousseau** [comment]
Closing as tickets have now been raised for the above
