### ISSUE TITLE
Features comparison with other SSGs ?

### ISSUE THREAD

**Issue by jrouaix** [sebastienrousseau/shokunin#114]
Hello @sebastienrousseau,

I was looking an SSG for a new project, and just stepped onto you project, and wonder how your lib compete with `zola` for example ?

Why did you start it in the first place ? What was your complain about the existing tools and thus what do you expect to do fundamentally better/easier/different ?

**Comment by sebastienrousseau** [comment]
@jrouaix Hi 👋 

I’ll be honest I haven’t done a full differential with any other SSG such as Zola or others. 

This project purely came from my personal needs on how I would like to generate websites and ensure they are automatically ready for SEO, accessibility etc.

No complaints on my side to any existing tools I fundamentally believe that there is no one that fits everybody needs.

This project is also a great practice ground to utilise Rust and see how best I can push the boundaries.

**Comment by jrouaix** [comment]
Haha, IMHO `Just because I wanted to do more Rust` is a perfect and enough answer to the `WHY?` question : CONGRATS !
