### ISSUE TITLE
Documentation on usage outside of templates?

### ISSUE THREAD

**Issue by Quackdoc** [sebastienrousseau/shokunin#186]
I was wondering if there was any documentation on how to actually use this outside of the code itself and the templates. I thought I'd try to take a look at making a blog out of this, but I haven't found any documents as to how to actually use this.

I can probably piece it together if there is no documentation already or documentation planned in the short term, but if there was I'd figure I'd would wait for it.

**Comment by sebastienrousseau** [comment]
At the moment I have not started this documentation, I have produced my own blog/website using SSG. Please feel free to check the source code on GitHub and see how I have combined the html and markdown to produce the results. I would be more than happy as well for you to contribute to Shokunin and extend the functionality and support
