### ISSUE TITLE
[Bug]: Missing examples

### ISSUE THREAD

**Issue by sebastienrousseau** [sebastienrousseau/shokunin#22]
❌ Missing examples both in the documentation and code base

- [x] Adding meaningful examples in code base
- [x] Adding meaningful examples in documentation
- [x] Documenting both on the README and code the examples

**Comment by HHocutt** [comment]
I'm planning on trying to run the examples when possible to learn and document the project.  Is this something I should try to do now or wait a bit until this bug is resolved?

**Comment by sebastienrousseau** [comment]
@HHocutt I have yet coded the examples, there are unit tests available and there is already some documentation available for you to consult in the meantime. Not sure when I'll be able to fix this bug but will endeavour to do it as soon as possible.

**Comment by sebastienrousseau** [comment]
@HHocutt Added a new example 🙂
