### ISSUE TITLE
[Documentation]: Complete shokunin documentation

### ISSUE THREAD

**Issue by sebastienrousseau** [sebastienrousseau/shokunin#24]
📚Complete shokunin documentation

- [x] Summary
- [x] Features
- [x] Examples and Usage
- [x] Contributing
- [x] License

**Comment by HHocutt** [comment]
I'm a technical writer, so I think I can help with some of the documentation.  I'll have to take some time to look through everything to make sure I understand your project.  If there are specific details that you would like to have included, let me know!

**Comment by sebastienrousseau** [comment]
@HHocutt Thanks!😊

What I am looking for is making sure the documentation follows Rust standards and best practices (https://doc.rust-lang.org/rustdoc/how-to-write-documentation.html) via Rustdoc. 

The aim is to be succinct by telling the user the What and the How in as little time as possible and using simple language, consistency and meaningful examples.

Anyway, do shout if you have any questions.

**Comment by HHocutt** [comment]
Sounds good!  I'll jump right in.
