### ISSUE TITLE
Pass the content of the "new" argument to compiler

### ISSUE THREAD

**Issue by Fubinator** [sebastienrousseau/shokunin#25]
Currently, the application name (provided by the cli's `new` flag) is not passed to the `compile` function. Instead, the site name is read with `let mut site_name = match env::args().nth(1)`. This leads to some awkward string manipulations to get the site's name:

https://github.com/sebastienrousseau/shokunin/blob/dc6817b3f6407a643992037495f5d2026a2188e7/src/lib.rs#L232-L237

I think passing the site's name directly from the `clap` matches would be better. This also makes sure, that the user can use the cli without using `=`.

For example:
`cargo run -- --new MY_SITE -c content/ -o dist`

**Comment by sebastienrousseau** [comment]
@Fubinator Good call and agree I was not very proud with the string manipulations 😃 Feel free to initiate a PR, thanks!
