### ISSUE TITLE
Templates

### ISSUE THREAD

**Issue by realtica** [sebastienrousseau/shokunin#89]
Hello,
Could you give us a pre-defined or compatible templates list?

**Comment by sebastienrousseau** [comment]
@realtica Yes I will. Let me know if there are any templates you are interested I can adapt them to work with Shokunin

**Comment by xixiaofinland** [comment]
The generator fails to run without a template. I'm also unsure what `template` files are demanded to get a default theme site up successfully.

As a new user, I expect to see a default site.

Steps:
1. I put a markdown file into the `content` folder 
2. run `ssg  -n=mysite -c=content -t=template -o=output -s=public`.
3. The Cli seeks a `template` file and panics.

**Comment by sebastienrousseau** [comment]
@realtica At the moment there's a template I have embedded in the `template` directory in the root folder called `Kaishi`. You can see the preview at <https://kaishi.one/>
