### ISSUE TITLE
Code blocks syntax high-light

### ISSUE THREAD

**Issue by xixiaofinland** [sebastienrousseau/shokunin#92]
It seems the code blocks are not supported in md files.
Is it possible to add this feature? 

Such as 
```
```ruby
require 'redcarpet'
markdown = Redcarpet.new("Hello World!")
puts markdown.to_html
```
```

**Comment by sebastienrousseau** [comment]
@xixiaofinland code blocks are supported. You will need to add them in the markdown as per this example: 

```

/* opening */```rust
use std::io;
/* closing */```

```

this would result in the following HTML:

```
<pre lang="rust"><code>use std::io;
</code></pre>
```
